---
title: "w5-india-for-fun"
author: "Sri Ramesh"
date: "4/7/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(raster)
library(leaflet)
library(tidyverse)
```

## A weather map of india for fun

```{r}
# India ----
IND_Adm0 <- raster::getData(name = "GADM", country = "IND", level = 0)

IND_prec_2.5 <- raster::getData(name = "worldclim", var = "prec",
                                res = 2.5)

# Restrict to Jul
IND_prec_2.5_Jul <- IND_prec_2.5[[7]]

# Crop and Mask to India extent 
IND_prec_2.5_Jul_Crop_Unmasked <- raster::crop(x = IND_prec_2.5_Jul,
                                             y = IND_Adm0)
IND_prec_2.5_Jul_Crop <- raster::mask(x = IND_prec_2.5_Jul_Crop_Unmasked,
                                    mask = IND_Adm0)

# Layer map
raster_colorPal_prec_JUL <- colorNumeric(palette = topo.colors(64),
                                         domain = values(IND_prec_2.5_Jul_Crop),
                                         na.color = NA)

leaflet() %>%
  addProviderTiles("CartoDB.Positron") %>%
  addRasterImage(x = IND_prec_2.5_Jul_Crop,
                 color = raster_colorPal_prec_JUL) %>%
  addPolygons(data = IND_Adm0,
              popup = IND_Adm0$NAME_0,
              label = IND_Adm0$NAME_0,
              fillOpacity = 0,
              color = "purple",
              weight = 3) %>%
  addLegend(title = "Jul precipitation (mm)<br>(2.5' res)",
            values = values(IND_prec_2.5_Jul_Crop),
            pal = raster_colorPal_prec_JUL)



```
